version: '3.7'
services: 
    app:
        container_name: devcontainercompose2_app
        build: .
        ports: 
            - 8000:8000
        volumes: 
            - ../app:/app
        tty: true
        depends_on: 
            - mysql
    mysql:
        container_name: devcontainercompose2_mysql
        image: mysql:5.7
        ports: 
            - 3306:3306
        environment: 
            MYSQL_ROOT_PASSWORD: M4st3rdb4
            MYSQL_USER: laravel_user
            MYSQL_PASSWORD: .s3cr3t0.
            MYSQL_DATABASE: laravel_db
        volumes:
            - ../data:/var/lib/mysql